import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:music_player/pages/playlist_page.dart';

class HomePage extends StatelessWidget {
  HomePage({super.key});

  final sad = [
    'song 0.ogg',
    'song 1.ogg',
    'song 10.ogg',
    'song 11.ogg',
    'song 12.ogg',
    'song 13.ogg',
    'song 14.ogg',
    'song 15.ogg',
    'song 16.ogg',
    'song 17.ogg',
    'song 18.ogg',
    'song 19.ogg',
    'song 2.ogg',
    'song 20.ogg',
    'song 21.ogg',
    'song 22.ogg',
    'song 23.ogg',
    'song 24.ogg',
    'song 25.ogg',
    'song 26.ogg',
    'song 27.ogg',
    'song 28.ogg',
    'song 29.ogg',
    'song 3.ogg',
    'song 30.ogg',
    'song 31.ogg',
    'song 32.ogg',
    'song 33.ogg',
    'song 34.ogg',
    'song 35.ogg',
    'song 36.ogg',
    'song 37.ogg',
    'song 38.ogg',
    'song 39.ogg',
    'song 4.ogg',
    'song 40.ogg',
    'song 41.ogg',
    'song 42.ogg',
    'song 43.ogg',
    'song 44.ogg',
    'song 45.ogg',
    'song 46.ogg',
    'song 47.ogg',
    'song 48.ogg',
    'song 49.ogg',
    'song 5.ogg',
    'song 50.ogg',
    'song 51.ogg',
    'song 52.ogg',
    'song 53.ogg',
    'song 54.ogg',
    'song 55.ogg',
    'song 56.ogg',
    'song 57.ogg',
    'song 58.ogg',
    'song 59.ogg',
    'song 6.ogg',
    'song 60.ogg',
    'song 61.ogg',
    'song 62.ogg',
    'song 63.ogg',
    'song 64.ogg',
    'song 65.ogg',
    'song 66.ogg',
    'song 67.ogg',
    'song 68.ogg',
    'song 69.ogg',
    'song 7.ogg',
    'song 70.ogg',
    'song 71.ogg',
    'song 72.ogg',
    'song 73.ogg',
    'song 74.ogg',
    'song 75.ogg',
    'song 76.ogg',
    'song 77.ogg',
    'song 78.ogg',
    'song 79.ogg',
    'song 8.ogg',
    'song 80.ogg',
    'song 81.ogg',
    'song 82.ogg',
    'song 83.ogg',
    'song 84.ogg',
    'song 9.ogg',
  ];

  final romantic = [
    'song 0.ogg',
    'song 1.ogg',
    'song 10.ogg',
    'song 11.ogg',
    'song 12.ogg',
    'song 13.ogg',
    'song 14.ogg',
    'song 15.ogg',
    'song 16.ogg',
    'song 17.ogg',
    'song 18.ogg',
    'song 19.ogg',
    'song 2.ogg',
    'song 20.ogg',
    'song 21.ogg',
    'song 22.ogg',
    'song 23.ogg',
    'song 24.ogg',
    'song 25.ogg',
    'song 26.ogg',
    'song 27.ogg',
    'song 28.ogg',
    'song 29.ogg',
    'song 3.ogg',
    'song 30.ogg',
    'song 31.ogg',
    'song 32.ogg',
    'song 33.ogg',
    'song 34.ogg',
    'song 35.ogg',
    'song 36.ogg',
    'song 37.ogg',
    'song 38.ogg',
    'song 39.ogg',
    'song 4.ogg',
    'song 40.ogg',
    'song 41.ogg',
    'song 42.ogg',
    'song 43.ogg',
    'song 44.ogg',
    'song 45.ogg',
    'song 46.ogg',
    'song 47.ogg',
    'song 48.ogg',
    'song 49.ogg',
    'song 5.ogg',
    'song 50.ogg',
    'song 51.ogg',
    'song 52.ogg',
    'song 53.ogg',
    'song 54.ogg',
    'song 55.ogg',
    'song 56.ogg',
    'song 57.ogg',
    'song 58.ogg',
    'song 59.ogg',
    'song 6.ogg',
    'song 60.ogg',
    'song 61.ogg',
    'song 62.ogg',
    'song 63.ogg',
    'song 64.ogg',
    'song 65.ogg',
    'song 66.ogg',
    'song 67.ogg',
    'song 68.ogg',
    'song 69.ogg',
    'song 7.ogg',
    'song 70.ogg',
    'song 71.ogg',
    'song 72.ogg',
    'song 73.ogg',
    'song 74.ogg',
    'song 75.ogg',
    'song 76.ogg',
    'song 77.ogg',
    'song 78.ogg',
    'song 79.ogg',
    'song 8.ogg',
    'song 80.ogg',
    'song 81.ogg',
    'song 82.ogg',
    'song 83.ogg',
    'song 84.ogg',
    'song 9.ogg',
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color.fromARGB(255, 21, 21, 21),
      appBar: AppBar(
        title: const Text(
          'Music Player',
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
        ),
        backgroundColor: Color.fromARGB(255, 21, 21, 21),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.only(top: 32),
          child: SingleChildScrollView(
            child: Column(
              spacing: 100,
              children: [
                SizedBox(
                  height: 300,
                  width: 300,
                  child: Image.asset('assets/images/screen.png'),
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    InkWell(
                      onTap: () => Get.to(
                        PlaylistPage(),
                        arguments: ["Playlist 1", romantic],
                      ),
                      child: SizedBox(
                        height: 90,
                        width: 100,
                        child: Card(
                          color: Color.fromARGB(255, 57, 57, 57),
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),

                            child: Center(
                              child: Text(
                                'Playlist 1',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 16,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),

                    InkWell(
                      onTap: () => Get.to(
                        PlaylistPage(),
                        arguments: ["Playlist 2", sad],
                      ),
                      child: SizedBox(
                        height: 90,
                        width: 100,
                        child: Card(
                          color: Color.fromARGB(255, 57, 57, 57),
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),

                            child: Center(
                              child: Text(
                                'Playlist 2',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 16,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),

                    InkWell(
                      onTap: () {
                        Get.to(PlaylistPage(), arguments: ["Favorite", []]);
                      },
                      child: SizedBox(
                        height: 90,
                        width: 100,
                        child: Card(
                          color: Color.fromARGB(255, 57, 57, 57),
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),

                            child: Center(
                              child: Text(
                                'Favorite',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 16,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
